import { SpinRecord, BankrollConfig, StrategyConfig } from '../types';
import { getNumberColor, getNumberDozen, getNumberColumn, getNumberParity, getNumberHalf } from './roulette';

export const INITIAL_BANKROLL_CONFIG: BankrollConfig = {
  initialBankroll: 100,
  dailyGoal: 20,
  stopLossLimit: 50,
  defaultSpinCost: 15,
  currency: 'R$',
  soundEnabled: true,
};

export const INITIAL_STRATEGY_CONFIG: StrategyConfig = {
  activePreset: 'top5_hot',
  dozen1Bet: 5,
  dozen2Bet: 5,
  dozen3Bet: 0,
  column1Bet: 0,
  column2Bet: 0,
  column3Bet: 0,
  straightNumberBets: { 0: 1, 15: 1, 30: 1, 19: 1, 31: 1 },
  colorRedBet: 0,
  colorBlackBet: 0,
};

export const DEMO_SPINS: SpinRecord[] = [
  {
    id: 'demo-1',
    giro: 1,
    numero: 1,
    color: getNumberColor(1),
    dozen: getNumberDozen(1),
    column: getNumberColumn(1),
    parity: getNumberParity(1),
    half: getNumberHalf(1),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:00:00',
  },
  {
    id: 'demo-2',
    giro: 2,
    numero: 15,
    color: getNumberColor(15),
    dozen: getNumberDozen(15),
    column: getNumberColumn(15),
    parity: getNumberParity(15),
    half: getNumberHalf(15),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N2',
    nextBetSuggestion: 'R$ 10 Col 1 / R$ 10 Col 3',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:02:00',
  },
  {
    id: 'demo-3',
    giro: 3,
    numero: 20,
    color: getNumberColor(20),
    dozen: getNumberDozen(20),
    column: getNumberColumn(20),
    parity: getNumberParity(20),
    half: getNumberHalf(20),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N3',
    nextBetSuggestion: 'R$ 15 Dúz 1 / R$ 15 Dúz 3',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:04:00',
  },
  {
    id: 'demo-4',
    giro: 4,
    numero: 14,
    color: getNumberColor(14),
    dozen: getNumberDozen(14),
    column: getNumberColumn(14),
    parity: getNumberParity(14),
    half: getNumberHalf(14),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:06:00',
  },
  {
    id: 'demo-5',
    giro: 5,
    numero: 36,
    color: getNumberColor(36),
    dozen: getNumberDozen(36),
    column: getNumberColumn(36),
    parity: getNumberParity(36),
    half: getNumberHalf(36),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N2',
    nextBetSuggestion: 'R$ 10 Col 1 / R$ 10 Col 3',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:08:00',
  },
  {
    id: 'demo-6',
    giro: 6,
    numero: 0,
    color: getNumberColor(0),
    dozen: getNumberDozen(0),
    column: getNumberColumn(0),
    parity: getNumberParity(0),
    half: getNumberHalf(0),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N3',
    nextBetSuggestion: 'R$ 15 Dúz 1 / R$ 15 Dúz 3',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:10:00',
  },
  {
    id: 'demo-7',
    giro: 7,
    numero: 12,
    color: getNumberColor(12),
    dozen: getNumberDozen(12),
    column: getNumberColumn(12),
    parity: getNumberParity(12),
    half: getNumberHalf(12),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:12:00',
  },
  {
    id: 'demo-8',
    giro: 8,
    numero: 29,
    color: getNumberColor(29),
    dozen: getNumberDozen(29),
    column: getNumberColumn(29),
    parity: getNumberParity(29),
    half: getNumberHalf(29),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N2',
    nextBetSuggestion: 'R$ 10 Col 1 / R$ 10 Col 3',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:14:00',
  },
  {
    id: 'demo-9',
    giro: 9,
    numero: 29,
    color: getNumberColor(29),
    dozen: getNumberDozen(29),
    column: getNumberColumn(29),
    parity: getNumberParity(29),
    half: getNumberHalf(29),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:16:00',
  },
  {
    id: 'demo-10',
    giro: 10,
    numero: 29,
    color: getNumberColor(29),
    dozen: getNumberDozen(29),
    column: getNumberColumn(29),
    parity: getNumberParity(29),
    half: getNumberHalf(29),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:18:00',
  },
  {
    id: 'demo-11',
    giro: 11,
    numero: 29,
    color: getNumberColor(29),
    dozen: getNumberDozen(29),
    column: getNumberColumn(29),
    parity: getNumberParity(29),
    half: getNumberHalf(29),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:20:00',
  },
  {
    id: 'demo-12',
    giro: 12,
    numero: 29,
    color: getNumberColor(29),
    dozen: getNumberDozen(29),
    column: getNumberColumn(29),
    parity: getNumberParity(29),
    half: getNumberHalf(29),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:22:00',
  },
  {
    id: 'demo-13',
    giro: 13,
    numero: 29,
    color: getNumberColor(29),
    dozen: getNumberDozen(29),
    column: getNumberColumn(29),
    parity: getNumberParity(29),
    half: getNumberHalf(29),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:24:00',
  },
  {
    id: 'demo-14',
    giro: 14,
    numero: 10,
    color: getNumberColor(10),
    dozen: getNumberDozen(10),
    column: getNumberColumn(10),
    parity: getNumberParity(10),
    half: getNumberHalf(10),
    winAmount: 0,
    lossAmount: 0,
    netResult: 0,
    accumulatedBalance: 100,
    botLevel: 'N1',
    nextBetSuggestion: 'R$ 10 no VERMELHO',
    cycleStatus: 'NEUTRAL',
    timestamp: '2026-07-23 10:26:00',
  },
];
